//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoUAQWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblexperiencia
    {
        public int idExperiencia { get; set; }
        public int idAspirante { get; set; }
        public string institucion { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        public virtual tblaspirante tblaspirante { get; set; }
    }
}
