//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoUAQWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsubcategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblsubcategoria()
        {
            this.tblofertas = new HashSet<tbloferta>();
            this.tblsubcategoriasusuarios = new HashSet<tblsubcategoriasusuario>();
        }
    
        public int cveSubcategoria { get; set; }
        public string descSubcategoria { get; set; }
        public Nullable<int> cveCategoria { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        public virtual tblcategoria tblcategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbloferta> tblofertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsubcategoriasusuario> tblsubcategoriasusuarios { get; set; }
    }
}
