//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoAUQService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TalentoUAQEntities : DbContext
    {
        public TalentoUAQEntities()
            : base("name=TalentoUAQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblaspirante> tblaspirantes { get; set; }
        public virtual DbSet<tblcategoria> tblcategorias { get; set; }
        public virtual DbSet<tblempresa> tblempresas { get; set; }
        public virtual DbSet<tblescolaridade> tblescolaridades { get; set; }
        public virtual DbSet<tblestado> tblestados { get; set; }
        public virtual DbSet<tblexperiencia> tblexperiencias { get; set; }
        public virtual DbSet<tblfavorito> tblfavoritos { get; set; }
        public virtual DbSet<tblidioma> tblidiomas { get; set; }
        public virtual DbSet<tblmunicipio> tblmunicipios { get; set; }
        public virtual DbSet<tbloferta> tblofertas { get; set; }
        public virtual DbSet<tblsubcategoria> tblsubcategorias { get; set; }
        public virtual DbSet<tblsubcategoriasusuario> tblsubcategoriasusuarios { get; set; }
        public virtual DbSet<tbltiposempleo> tbltiposempleos { get; set; }
    }
}
