//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoAUQService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbloferta()
        {
            this.tblfavoritos = new HashSet<tblfavorito>();
        }
    
        public int idOferta { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> sueldoInicio { get; set; }
        public Nullable<int> sueldoFin { get; set; }
        public Nullable<System.DateTime> fechaInicioOferta { get; set; }
        public Nullable<System.DateTime> fechaFinOferta { get; set; }
        public Nullable<int> cveEmpresa { get; set; }
        public string nombreContacto { get; set; }
        public string correoContacto { get; set; }
        public string telefonoContacto { get; set; }
        public Nullable<int> cveTipoEmpleo { get; set; }
        public Nullable<int> cveSubcategoria { get; set; }
        public Nullable<int> cveMunicipio { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        public virtual tblempresa tblempresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfavorito> tblfavoritos { get; set; }
        public virtual tblmunicipio tblmunicipio { get; set; }
        public virtual tblsubcategoria tblsubcategoria { get; set; }
        public virtual tbltiposempleo tbltiposempleo { get; set; }
    }
}
